/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/japanese_bridge_garden.glb 
Author: kristenlee (https://sketchfab.com/kristenlee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-bridge-garden-d122e17593eb4012913cde927486d15a
Title: Japanese Bridge Garden
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function JapaneseBridgeGarden(props) {
  const { nodes, materials } = useGLTF('./models/japanese_bridge_garden.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-304.428, 14.265, -342.798]} rotation={[-Math.PI / 2, 0, -2.385]} scale={13.176}>
          <mesh geometry={nodes.Cylinder001_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder001_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder001_Material003_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[-143.761, 344.932, -106.9]} rotation={[-Math.PI / 2, 0, 0]} scale={7.174}>
          <mesh geometry={nodes.Cylinder002_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder002_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cylinder002_Material004_0.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-7.852, 67.68, 2.949]} rotation={[-Math.PI / 2, 0, 0]} scale={[64.752, 4.714, 6.404]}>
          <mesh geometry={nodes.Cube005_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube005_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube005_Material007_0.geometry} material={materials['Material.007']} />
        </group>
        <group position={[116.563, 413.675, -314.775]} rotation={[-1.75, 1.01, 0.029]} scale={29.644}>
          <mesh geometry={nodes.Icosphere016_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Icosphere016_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Icosphere016_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[469.429, 421.78, -411.865]} rotation={[-Math.PI / 2, 0, -0.293]} scale={14.114}>
          <mesh geometry={nodes.Cylinder003_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder003_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder003_Material003_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[-468.024, 500.944, 399.734]} rotation={[-Math.PI / 2, 0, -1.546]} scale={17.685}>
          <mesh geometry={nodes.Cylinder005_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder005_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder005_Material003_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[-201.053, 326.72, -414.339]} rotation={[-Math.PI / 2, 0, -3.065]} scale={16.965}>
          <mesh geometry={nodes.Cylinder006_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder006_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[374.464, 273.072, -454.306]} rotation={[-Math.PI / 2, 0, -3.065]} scale={13.152}>
          <mesh geometry={nodes.Cylinder007_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder007_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-446.421, 297.556, 249.731]} rotation={[-Math.PI / 2, 0, -2.219]} scale={15.546}>
          <mesh geometry={nodes.Cylinder004_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder004_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-423.998, 248.44, 336.471]} rotation={[-Math.PI / 2, 0, 0.356]} scale={11.25}>
          <mesh geometry={nodes.Cylinder008_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder008_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[273.911, 90.37, -403.956]} rotation={[-Math.PI / 2, 0, 0]} scale={[19.756, 19.756, 31.625]}>
          <mesh geometry={nodes.Circle_Material010_0.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Circle_Material003_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[-468.33, 399.074, 551.43]} rotation={[0.046, -0.284, 2.777]} scale={26.669}>
          <mesh geometry={nodes.Icosphere010_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Icosphere010_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-96.28, 373.126, -462.897]} rotation={[-1.13, -0.954, -2.799]} scale={20.32}>
          <mesh geometry={nodes.Icosphere001_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Icosphere001_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Icosphere001_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-13.308, 55.578, 12.503]} rotation={[-Math.PI / 2, 0, 0]} scale={[539.41, 514.638, 17.828]}>
          <mesh geometry={nodes.Cube_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Cube_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[163.912, 579.277, -177.118]} rotation={[-Math.PI / 2, 0, 0.89]} scale={7.174}>
          <mesh geometry={nodes.Cylinder009_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder009_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cylinder009_Material004_0.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-203.961, 538.925, 86.053]} rotation={[-Math.PI / 2, 0, 1.18]} scale={7.174}>
          <mesh geometry={nodes.Cylinder010_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder010_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cylinder010_Material004_0.geometry} material={materials['Material.004']} />
        </group>
        <group position={[0.242, 655.785, 42.97]} rotation={[-Math.PI / 2, 0, 1.18]} scale={7.174}>
          <mesh geometry={nodes.Cylinder011_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder011_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cylinder011_Material004_0.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-183.478, 130.395, 151.001]} rotation={[-Math.PI / 2, 0, 0]} scale={7.174}>
          <mesh geometry={nodes.Cylinder012_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder012_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cylinder012_Material004_0.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-11.389, 130.395, 211.401]} rotation={[-Math.PI / 2, 0, 0]} scale={7.174}>
          <mesh geometry={nodes.Cylinder013_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder013_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cylinder013_Material004_0.geometry} material={materials['Material.004']} />
        </group>
        <mesh geometry={nodes.Plane003_Material005_0.geometry} material={materials['Material.005']} position={[0, 106.663, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={565.211} />
        <mesh geometry={nodes.Icosphere018_Material003_0.geometry} material={materials['Material.003']} position={[432.383, 108.865, -344.693]} rotation={[-Math.PI / 2, 0, -2.981]} scale={[45.94, 45.94, 78.14]} />
        <mesh geometry={nodes.Icosphere017_Material003_0.geometry} material={materials['Material.003']} position={[-400.453, 108.865, -409.787]} rotation={[-Math.PI / 2, 0, -2.032]} scale={[52.701, 52.701, 89.64]} />
        <mesh geometry={nodes.Circle001_Material011_0.geometry} material={materials['Material.011']} position={[-107.323, 107.058, 313.979]} rotation={[-Math.PI / 2, 0, 0.599]} scale={30.611} />
        <mesh geometry={nodes.Circle002_Material011_0.geometry} material={materials['Material.011']} position={[-158.118, 107.058, 272.823]} rotation={[-Math.PI / 2, 0, 1.961]} scale={30.611} />
        <mesh geometry={nodes.Circle003_Material011_0.geometry} material={materials['Material.011']} position={[-29.81, 107.058, 340.017]} rotation={[-Math.PI / 2, 0, -1.044]} scale={25.391} />
        <mesh geometry={nodes.Circle004_Material011_0.geometry} material={materials['Material.011']} position={[-44.266, 107.058, 260.842]} rotation={[-Math.PI / 2, 0, 2.951]} scale={34.278} />
        <mesh geometry={nodes.Circle005_Material011_0.geometry} material={materials['Material.011']} position={[-111.113, 107.058, 272.823]} rotation={[-Math.PI / 2, 0, -2.425]} scale={30.611} />
        <mesh geometry={nodes.Circle006_Material011_0.geometry} material={materials['Material.011']} position={[-58.146, 107.058, 295.342]} rotation={[-Math.PI / 2, 0, -1.695]} scale={24.846} />
        <mesh geometry={nodes.Circle007_Material011_0.geometry} material={materials['Material.011']} position={[79.513, 107.058, -270.805]} rotation={[-Math.PI / 2, 0, 2.015]} scale={30.611} />
        <mesh geometry={nodes.Circle008_Material011_0.geometry} material={materials['Material.011']} position={[-20.47, 107.058, -252.289]} rotation={[-Math.PI / 2, 0, -2.907]} scale={30.611} />
        <mesh geometry={nodes.Circle009_Material011_0.geometry} material={materials['Material.011']} position={[117.2, 107.058, -317.37]} rotation={[-Math.PI / 2, 0, 0.372]} scale={25.391} />
        <mesh geometry={nodes.Circle010_Material011_0.geometry} material={materials['Material.011']} position={[36.743, 107.058, -315.305]} rotation={[-Math.PI / 2, 0, -1.916]} scale={34.278} />
        <mesh geometry={nodes.Circle011_Material011_0.geometry} material={materials['Material.011']} position={[38.264, 107.058, -263.993]} rotation={[-Math.PI / 2, 0, -1.009]} scale={30.611} />
        <mesh geometry={nodes.Circle012_Material011_0.geometry} material={materials['Material.011']} position={[73.222, 107.058, -327.701]} rotation={[-Math.PI / 2, 0, 1.264]} scale={24.846} />
        <mesh geometry={nodes.Circle013_Material011_0.geometry} material={materials['Material.011']} position={[112.808, 107.058, -252.289]} rotation={[-Math.PI / 2, 0, -2]} scale={25.982} />
        <mesh geometry={nodes.Circle014_Material011_0.geometry} material={materials['Material.011']} position={[-111.113, 107.058, 139.578]} rotation={[-Math.PI / 2, 0, -2.425]} scale={39.892} />
        <mesh geometry={nodes.Succulent_Material012_0.geometry} material={materials['Material.012']} position={[-114.288, 107.742, 298.336]} rotation={[0.977, -0.294, -2.736]} scale={[-2.266, 2.266, 11.456]} />
        <mesh geometry={nodes.Succulent001_Material012_0.geometry} material={materials['Material.012']} position={[-126.327, 108.04, 134.391]} rotation={[1.778, 0.626, 1.227]} scale={[-2.568, 2.568, 12.985]} />
        <mesh geometry={nodes.Succulent002_Material012_0.geometry} material={materials['Material.012']} position={[-26.581, 107.742, 298.336]} rotation={[2.173, 0.276, 0.377]} scale={[-2.715, 2.715, 13.724]} />
        <mesh geometry={nodes.Succulent003_Material012_0.geometry} material={materials['Material.012']} position={[41.111, 108.04, -264.512]} rotation={[2.039, 0.476, 0.737]} scale={[-3.281, 3.281, 16.59]} />
        <mesh geometry={nodes.Succulent004_Material012_0.geometry} material={materials['Material.012']} position={[96.462, 108.04, -308.508]} rotation={[2.215, -0.129, -0.17]} scale={[-2.35, 2.35, 11.88]} />
        <mesh geometry={nodes.Succulent005_Material012_0.geometry} material={materials['Material.012']} position={[110.197, 108.04, -260.363]} rotation={[2.044, -0.471, -0.726]} scale={[-1.867, 1.867, 9.438]} />
        <mesh geometry={nodes.Plane001_Material009_0.geometry} material={materials['Material.009']} position={[374.429, 113.25, 7.068]} rotation={[-Math.PI / 2, 0, -1.76]} scale={37.526} />
        <mesh geometry={nodes.Plane002_Material009_0.geometry} material={materials['Material.009']} position={[407.175, 113.25, -57.162]} rotation={[-Math.PI / 2, 0, -0.255]} scale={32.653} />
        <mesh geometry={nodes.Plane004_Material009_0.geometry} material={materials['Material.009']} position={[437.139, 113.25, -5.06]} rotation={[-Math.PI / 2, 0, 3.002]} scale={29.773} />
        <mesh geometry={nodes.Plane005_Material009_0.geometry} material={materials['Material.009']} position={[417.587, 113.25, 29.904]} rotation={[-Math.PI / 2, 0, -2.049]} scale={24.469} />
        <mesh geometry={nodes.Plane006_Material009_0.geometry} material={materials['Material.009']} position={[455.85, 113.25, 29.904]} rotation={[-Math.PI / 2, 0, -1.146]} scale={21.182} />
        <mesh geometry={nodes.Plane007_Material009_0.geometry} material={materials['Material.009']} position={[-385.16, 113.25, -28.092]} rotation={[-Math.PI / 2, 0, 1.593]} scale={37.526} />
        <mesh geometry={nodes.Plane008_Material009_0.geometry} material={materials['Material.009']} position={[-403.724, 113.25, 41.573]} rotation={[-Math.PI / 2, 0, 3.098]} scale={32.653} />
        <mesh geometry={nodes.Plane009_Material009_0.geometry} material={materials['Material.009']} position={[-443.938, 113.25, -3.097]} rotation={[-Math.PI / 2, 0, 0.072]} scale={29.773} />
        <mesh geometry={nodes.Plane010_Material009_0.geometry} material={materials['Material.009']} position={[-432.144, 113.25, -41.381]} rotation={[-Math.PI / 2, 0, 1.303]} scale={24.469} />
        <mesh geometry={nodes.Plane011_Material009_0.geometry} material={materials['Material.009']} position={[-469.558, 113.25, -33.365]} rotation={[-Math.PI / 2, 0, 2.207]} scale={21.182} />
        <mesh geometry={nodes.Cube009_Material003_0.geometry} material={materials['Material.003']} position={[416.719, 93.434, -249.362]} rotation={[-1.633, 0.189, -2.82]} scale={[0.706, 0.261, 0.464]} />
        <mesh geometry={nodes.Cube002_Material003_0.geometry} material={materials['Material.003']} position={[333.247, 98.688, -285.448]} rotation={[-1.417, 0.127, 2.256]} scale={[0.706, 0.261, 0.464]} />
        <mesh geometry={nodes.Cube003_Material003_0.geometry} material={materials['Material.003']} position={[342.047, 105.476, 125.152]} rotation={[-1.491, -0.182, -2.723]} scale={[-0.644, 0.389, 0.406]} />
        <mesh geometry={nodes.Cube006_Material003_0.geometry} material={materials['Material.003']} position={[-367.121, 103.368, -278.318]} rotation={[-1.676, 0.169, -2.582]} scale={[0.582, 0.215, 0.383]} />
        <mesh geometry={nodes.Cube007_Material003_0.geometry} material={materials['Material.003']} position={[-464.72, 98.227, -296.039]} rotation={[-1.485, 0.179, 2.691]} scale={[0.582, 0.215, 0.383]} />
        <mesh geometry={nodes.Cube008_Material003_0.geometry} material={materials['Material.003']} position={[-142.915, 103.368, -278.318]} rotation={[-1.511, 0.19, 2.835]} scale={[0.483, 0.179, 0.318]} />
        <mesh geometry={nodes.Cube010_Material003_0.geometry} material={materials['Material.003']} position={[-386.25, 98.548, 277.424]} rotation={[-1.756, -0.073, -1.201]} scale={[0.65, 0.35, 0.385]} />
        <mesh geometry={nodes.Cube011_Material003_0.geometry} material={materials['Material.003']} position={[-397.882, 102.878, 347.87]} rotation={[-1.708, 0.144, -2.377]} scale={[0.817, 0.296, 0.39]} />
        <mesh geometry={nodes.Cube012_Material003_0.geometry} material={materials['Material.003']} position={[-395.476, 102.878, 434.852]} rotation={[-1.509, -0.189, 0.317]} scale={[0.598, 0.271, 0.383]} />
        <mesh geometry={nodes.Cube013_Material003_0.geometry} material={materials['Material.003']} position={[8.256, 100.952, 452.761]} rotation={[-1.652, 0.181, -2.717]} scale={[0.707, 0.186, 0.295]} />
        <mesh geometry={nodes.Icosphere002_Material003_0.geometry} material={materials['Material.003']} position={[-278.348, 108.865, 421.275]} rotation={[-Math.PI / 2, 0, -0.82]} scale={[36.499, 36.499, 62.082]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/japanese_bridge_garden.glb')
