/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low_poly_lighthouse_scene.glb
Author: kristenlee (https://sketchfab.com/kristenlee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-lighthouse-scene-7cbc357ed5ce44a1bf723c13b9b212d1
Title: Low Poly Lighthouse Scene
*/

import React, { useRef, useEffect } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { useStore } from '../store/store.js';
import { enableModelShadows } from '../utils/enableModelShadows.js';
import * as THREE from 'three';

export function LightHouse(props) {
  const { nodes, materials } = useGLTF('./models/low_poly_lighthouse_scene.glb');
  const { gameStarted, foundDifferences, markDifferenceFound } = useStore();
  const seaRef = useRef();
  const modelRef = useRef();
  let time = useRef(0);

  useEffect(() => {
    if (modelRef.current) {
      const box = new THREE.Box3().setFromObject(modelRef.current);
      const center = new THREE.Vector3();
      box.getCenter(center);
      modelRef.current.position.set(-center.x, -center.y, -center.z);
      enableModelShadows(modelRef.current);
    }
  }, []);

  useFrame((state, delta) => {
    if (seaRef.current) {
      time.current += delta;
      seaRef.current.position.y = -380.538 + Math.sin(time.current * 1) * 3;
    }
  });

  const handleClick = (id) => {
    if (!gameStarted) return;
    if (!foundDifferences.includes(id)) {
      markDifferenceFound(id);
    }
  };

  return (
    <group ref={modelRef} {...props} dispose={null}>
      <group scale={0.002}>
        <group position={[160.969, -237.542, 169.454]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Circle_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Circle_Material005_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Circle_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Circle_Material004_0.geometry} material={materials['Material.004']} />
          <mesh
              geometry={nodes.Circle_Material001_0.geometry}
              material={materials['Material.001']}
              onClick={() => handleClick('diff1')}
              material-transparent
              material-opacity={gameStarted && !foundDifferences.includes('diff1') ? 0 : 1}
          />
        </group>
        <group position={[231.662, -222.199, 244.591]} rotation={[-1.502, 0, 0.377]} scale={[55.009, 33.275, 33.275]}>
          <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube_Material005_0.geometry} material={materials['Material.005']} />
          <mesh
              geometry={nodes.Cube_Material010_0.geometry}
              material={materials['Material.010']}
              onClick={() => handleClick('diff2')}
              material-transparent
              material-opacity={gameStarted && !foundDifferences.includes('diff2') ? 0 : 1}
          />
        </group>
        <mesh geometry={nodes.Circle002__0.geometry} material={materials['Circle.002__0']} position={[160.969, 254.448, 169.454]} rotation={[-Math.PI / 2, 0, 0.777]} scale={100} />
        <mesh
            geometry={nodes.Circle001_Light_0.geometry}
            material={materials.Light}
            position={[160.969, -238.164, 169.454]}
            rotation={[-Math.PI / 2, 0, 0]} scale={100}
            onClick={() => handleClick('diff3')}
            material-transparent
            material-opacity={gameStarted && !foundDifferences.includes('diff3') ? 0 : 1}
        />
        <mesh geometry={nodes.Cube001_Rocks_0.geometry} material={materials.Rocks} position={[395.73, -418.676, 296.939]} rotation={[-0.854, 0.033, -3.104]} scale={172.239} />
        <mesh geometry={nodes.Cube002_Rocks_0.geometry} material={materials.Rocks} position={[536.559, -447.358, 314.495]} rotation={[-2.255, -0.234, 0.277]} scale={117.564} />
        <mesh
            ref={seaRef}
            geometry={nodes.Sea_Material006_0.geometry}
            material={materials['Material.006']}
            position={[279.622, -380.538, 239.745]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[16.328, 16.328, 17.851]}
        />
        <mesh geometry={nodes.Cube003_Rocks_0.geometry} material={materials.Rocks} position={[-63.345, -384.83, 280.083]} rotation={[-1.004, -0.284, -3.137]} scale={68.278} />
        <mesh geometry={nodes.Cube004_Rocks_0.geometry} material={materials.Rocks} position={[249.637, -390.33, 367.886]} rotation={[-2.554, 0.484, 0.12]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube005_Rocks_0.geometry} material={materials.Rocks} position={[452.713, -371.453, 55.819]} rotation={[-0.513, -0.003, -2.722]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube006_Rocks_0.geometry} material={materials.Rocks} position={[226.152, -381.869, 5.03]} rotation={[2.633, -0.003, -2.722]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube007_Rocks_0.geometry} material={materials.Rocks} position={[501.83, -511.269, 456.531]} rotation={[-2.554, 0.484, 0.12]} scale={[12.83, 16.065, 15.26]} />
        <mesh geometry={nodes.Cube008_Rocks_0.geometry} material={materials.Rocks} position={[73.76, -538.511, 646.418]} rotation={[0.998, 0.314, 0.025]} scale={[26.493, 56.98, 48.993]} />
        <mesh geometry={nodes.Sand_Sand_0.geometry} material={materials.Sand} position={[278.919, -638.272, 234.345]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.238, 15.895, 19.928]} />
        <mesh geometry={nodes.Cube009_Rocks_0.geometry} material={materials.Rocks} position={[514.453, -693.462, 579.682]} rotation={[2.616, -0.741, -2.151]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube010_Rocks_0.geometry} material={materials.Rocks} position={[731.944, -679.982, 380.359]} rotation={[0.44, 0.517, 1.135]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube011_Rocks_0.geometry} material={materials.Rocks} position={[195.337, -653.276, 487.151]} rotation={[2.757, -0.163, -1.843]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube012_Rocks_0.geometry} material={materials.Rocks} position={[107.631, -441.201, 374.163]} rotation={[0.395, 1.108, 1.724]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube013_Rocks_0.geometry} material={materials.Rocks} position={[177.514, -449.972, 460.807]} rotation={[0.19, -0.051, 2.321]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube014_Rocks_0.geometry} material={materials.Rocks} position={[417.606, -447.222, 382.564]} rotation={[0.174, -0.074, 2.229]} scale={[49.492, 61.971, 58.865]} />
        <mesh geometry={nodes.Cube015_Rocks_0.geometry} material={materials.Rocks} position={[198.449, -272.261, 271.338]} rotation={[-1.004, -0.284, -3.137]} scale={15.47} />
        <mesh geometry={nodes.Cube016_Rocks_0.geometry} material={materials.Rocks} position={[358.394, -267.404, 275.219]} rotation={[-2.151, -0.252, 0.783]} scale={15.47} />
        <mesh geometry={nodes.Cube017_Rocks_0.geometry} material={materials.Rocks} position={[32.074, -251.04, 151.373]} rotation={[-2.151, -0.252, 0.783]} scale={15.47} />
        <mesh geometry={nodes.Cube018_Rocks_0.geometry} material={materials.Rocks} position={[329.526, -317.478, 353.69]} rotation={[-1.458, -0.252, 0.783]} scale={15.47} />
        <mesh geometry={nodes.Cube019_Rocks_0.geometry} material={materials.Rocks} position={[192.906, -451.75, 397.999]} rotation={[-1.004, -0.284, -3.137]} scale={64.917} />
        <mesh geometry={nodes.Cube020_Rocks_0.geometry} material={materials.Rocks} position={[333.707, -456.858, 460.573]} rotation={[-2.137, 0.284, 0.005]} scale={64.917} />
        <mesh geometry={nodes.Cube021_Rocks_0.geometry} material={materials.Rocks} position={[-9.454, -510.926, 135.136]} rotation={[-2.037, 0.012, 0.963]} scale={172.239} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/low_poly_lighthouse_scene.glb')
