/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/western_diorama_-_low_poly.glb
Author: libblekibble (https://sketchfab.com/libblekibble)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/western-diorama-low-poly-0824a6a99b71436da5ea75b2313f73ea
Title: Western Diorama - Low Poly
*/

import React, { useEffect, useRef, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { enableModelShadows } from '../utils/enableModelShadows.js';
import { useStore } from '../store/store.js';

function isHidden(gameStarted, activeHiddenIds, foundDifferences, id) {
    return gameStarted && activeHiddenIds.includes(id) && !foundDifferences.includes(id);
}

export function WesternDiorama(props) {
    const { nodes, materials } = useGLTF('./models/western_diorama_-_low_poly.glb');
    const { gameStarted, foundDifferences, activeHiddenIds, markDifferenceFound } = useStore();
    const modelRef = useRef();

    const matTanX = useMemo(() => materials['building_tan.001'].clone(), [materials]);
    const matTanW = useMemo(() => materials['building_tan.001'].clone(), [materials]);
    const matPlantY = useMemo(() => materials.PLANT.clone(), [materials]);
    const matPlantV = useMemo(() => materials.PLANT.clone(), [materials]);
    const matBrownZ = useMemo(() => materials.building_brown.clone(), [materials]);

    useEffect(() => {
        [matTanX, matTanW, matPlantY, matPlantV, matBrownZ].forEach((m) => {
            m.transparent = true;
        });
    }, [matTanX, matTanW, matPlantY, matPlantV, matBrownZ]);

    useEffect(() => {
        if (modelRef.current) {
            const box = new THREE.Box3().setFromObject(modelRef.current);
            const center = new THREE.Vector3();
            box.getCenter(center);
            modelRef.current.position.set(-center.x, -center.y, -center.z);
            enableModelShadows(modelRef.current);
        }
    }, []);

    const handleClick = (id) => {
        if (!gameStarted) return;
        if (!foundDifferences.includes(id)) {
            markDifferenceFound(id);
        }
    };

    const h = (id) => (isHidden(gameStarted, activeHiddenIds, foundDifferences, id) ? 0 : 1);

    return (
        <group ref={modelRef} {...props} dispose={null}>
            <group scale={0.0032}>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Plane001_building_tan001_0.geometry} material={materials['building_tan.001']} />
                    <mesh geometry={nodes.Plane001_Material001_0.geometry} material={materials['Material.001']} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Plane002_Material007_0.geometry} material={materials['Material.007']} />
                    <mesh geometry={nodes.Plane002_Material002_0.geometry} material={materials['Material.002']} />
                    <mesh geometry={nodes.Plane002_wood_dark_0.geometry} material={materials.wood_dark} />
                    <mesh geometry={nodes.Plane002_building_brown_0.geometry} material={materials.building_brown} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Cube005_wood_dark_0.geometry} material={materials.wood_dark} />
                    <mesh geometry={nodes.Cube005_building_yellow_0.geometry} material={materials.building_yellow} />
                    <mesh geometry={nodes.Cube005_Material002_0.geometry} material={materials['Material.002']} />
                    <mesh geometry={nodes.Cube005_window_emission_0.geometry} material={materials.window_emission} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Plane006_church_main_0.geometry} material={materials.church_main} />
                    <mesh geometry={nodes.Plane006_wood_dark_0.geometry} material={materials.wood_dark} />
                    <mesh geometry={nodes.Plane006_window_emission_0.geometry} material={materials.window_emission} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Cube006_building_tan_0.geometry} material={materials.building_tan} />
                    <mesh geometry={nodes.Cube006_building_brown_0.geometry} material={materials.building_brown} />
                    <mesh geometry={nodes.Cube006_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Plane013_building_brown_0.geometry} material={materials.building_brown} />
                    <mesh geometry={nodes.Plane013_church_main_0.geometry} material={materials.church_main} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Plane014_building_brown_0.geometry} material={materials.building_brown} />
                    <mesh geometry={nodes.Plane014_church_main_0.geometry} material={materials.church_main} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Circle003_Material_0.geometry} material={materials.Material} />
                    <mesh geometry={nodes.Circle003_Material002_0.geometry} material={materials['Material.002']} />
                    <mesh geometry={nodes.Circle003_church_main_0.geometry} material={materials.church_main} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Circle004_Material_0.geometry} material={materials.Material} />
                    <mesh geometry={nodes.Circle004_Material002_0.geometry} material={materials['Material.002']} />
                    <mesh geometry={nodes.Circle004_church_main_0.geometry} material={materials.church_main} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.Plane024_building_brown_0.geometry} material={materials.building_brown} />
                    <mesh geometry={nodes.Plane024_church_main_0.geometry} material={materials.church_main} />
                </group>
                <mesh geometry={nodes.Plane007_wood_dark_0.geometry} material={materials.wood_dark} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Circle001_building_brown_0.geometry} material={materials.building_brown} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh
                    geometry={nodes.Icosphere003_building_tan001_0.geometry}
                    material={matTanX}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                    onClick={() => handleClick('diffX')}
                    material-opacity={h('diffX')}
                />
                <mesh geometry={nodes.Icosphere002_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh
                    geometry={nodes.Icosphere001_building_tan001_0.geometry}
                    material={matTanW}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                    onClick={() => handleClick('diffW')}
                    material-opacity={h('diffW')}
                />
                <mesh geometry={nodes.Icosphere004_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere005_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh
                    geometry={nodes.Plane016_PLANT_0.geometry}
                    material={matPlantY}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                    onClick={() => handleClick('diffY')}
                    material-opacity={h('diffY')}
                />
                <mesh geometry={nodes.Plane008_PLANT_0.geometry} material={materials.PLANT} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere006_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh
                    geometry={nodes.Plane017_PLANT_0.geometry}
                    material={matPlantV}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                    onClick={() => handleClick('diffV')}
                    material-opacity={h('diffV')}
                />
                <mesh geometry={nodes.Plane020_PLANT_0.geometry} material={materials.PLANT} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Plane022_PLANT_0.geometry} material={materials.PLANT} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Plane023_PLANT_0.geometry} material={materials.PLANT} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere007_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere008_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere009_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere010_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere011_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh
                    geometry={nodes.Circle005_building_brown_0.geometry}
                    material={matBrownZ}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                    onClick={() => handleClick('diffZ')}
                    material-opacity={h('diffZ')}
                />
                <mesh geometry={nodes.Icosphere012_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere013_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere014_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere015_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere016_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere017_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <mesh geometry={nodes.Icosphere018_building_tan001_0.geometry} material={materials['building_tan.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
        </group>
    );
}

useGLTF.preload('./models/western_diorama_-_low_poly.glb');
