/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wheat_farm_at_sunset.glb
Author: kristenlee (https://sketchfab.com/kristenlee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wheat-farm-at-sunset-a324ba0bdf95402ba61f153852dc3312
Title: Wheat Farm At Sunset
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from "three";
import { enableModelShadows } from '../utils/enableModelShadows.js';


export function WheatFarm(props) {
  const { nodes, materials } = useGLTF('./models/wheat_farm_at_sunset.glb')
  const modelRef = useRef();
  /** Pás do moinho — animação só para dar vida à cena (não é um dos erros do jogo). */
  const windmillBladesRef = useRef();

  useFrame((state, delta) => {
    const increment = 0.2 * delta;
    if (windmillBladesRef.current) windmillBladesRef.current.rotation.x += increment;
  });

  useEffect(() => {
    if (modelRef.current) {
      const box = new THREE.Box3().setFromObject(modelRef.current);
      const center = new THREE.Vector3();
      box.getCenter(center);
      modelRef.current.position.set(-center.x, -center.y, -center.z);
      enableModelShadows(modelRef.current);
    }
  }, []);

  return (
      <group ref={modelRef} {...props} dispose={null}>
        <group scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane_Ground_0.geometry} material={materials.Ground} />
            <mesh geometry={nodes.Plane_Green_0.geometry} material={materials.Green} />
          </group>
          <group position={[-41.401, 8.149, 28.668]} rotation={[-Math.PI / 2, 0, 0]} scale={40.43}>
            <mesh geometry={nodes.Circle_Tiles_0.geometry} material={materials.Tiles} />
            <mesh geometry={nodes.Circle_WindmillWalls_0.geometry} material={materials.WindmillWalls} />
            <mesh geometry={nodes.Circle_Balcony_0.geometry} material={materials.Balcony} />
          </group>
          <group position={[-41.401, 81.882, 61.651]} rotation={[-Math.PI / 2, 0, 0]} scale={[70.925, 70.925, 60.38]}>
            <mesh geometry={nodes.Cube004_Fence001_0.geometry} material={materials['Fence.001']} />
            <mesh geometry={nodes.Cube004_Ground_0.geometry} material={materials.Ground} />
          </group>
          <group ref={windmillBladesRef} position={[11.822, 129.965, 28.668]} rotation={[-1.897, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane005_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Plane005_Ground_0.geometry} material={materials.Ground} />
          </group>
          <mesh geometry={nodes.Cube001_DoorRock_0.geometry} material={materials.DoorRock} position={[-5.968, 29.418, 28.689]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 112.151, 100]} />
          <mesh geometry={nodes.Plane001_Fence001_0.geometry} material={materials['Fence.001']} position={[-5.55, 29.418, 28.689]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={11.908} />
          <mesh geometry={nodes.Cube002_DoorRock001_0.geometry} material={materials['DoorRock.001']} position={[-5.968, 29.418, 28.689]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 112.151, 100]} />
          <mesh geometry={nodes.Plane002_DoorRock_0.geometry} material={materials.DoorRock} position={[1.057, 3.168, 28.668]} rotation={[-Math.PI / 2, 0, 0]} scale={[11.231, 14.045, 11.231]} />
          <mesh geometry={nodes.Cylinder_Ground_0.geometry} material={materials.Ground} position={[-22.995, 129.965, 28.668]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cube003_Fence001_0.geometry} material={materials['Fence.001']} position={[-19.163, 95.496, 50.428]} rotation={[-Math.PI / 2, 0, 0.832]} scale={70.925} />
          <mesh geometry={nodes.Cube005_Balcony_0.geometry} material={materials.Balcony} position={[-41.703, 63.41, 28.668]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube_Fence_0.geometry} material={materials.Fence} position={[-7.679, 21.353, -104.389]} rotation={[-Math.PI / 2, -0.093, Math.PI / 2]} scale={[3.159, 4.567, 3.171]} />
          <mesh geometry={nodes.Cube006_Fence_0.geometry} material={materials.Fence} position={[-51.385, 15.977, -59.87]} rotation={[-1.52, 0, -Math.PI]} scale={[2.892, 3.998, 2.897]} />
          <mesh geometry={nodes.Cube013_Rocks_0.geometry} material={materials.Rocks} position={[79.072, -3.309, 49.157]} rotation={[1.348, -0.271, -1.068]} scale={[8.108, 8.2, 11.808]} />
          <mesh geometry={nodes.Cube015_Rocks_0.geometry} material={materials.Rocks} position={[26.22, 14.461, -84.43]} rotation={[-1.296, -0.175, 1.998]} scale={[9.786, 9.896, 14.251]} />
          <mesh geometry={nodes.Cube016_Rocks_0.geometry} material={materials.Rocks} position={[-65.588, -1.141, 67.824]} rotation={[-1.791, 0.239, -0.955]} scale={[27.533, 22.934, 23.157]} />
          <mesh geometry={nodes.Cube037_Wheat_0.geometry} material={materials.Wheat} position={[11.662, 19.227, -63.095]} rotation={[-1.608, -0.064, 1.024]} scale={[1.138, 1.138, 0.801]} />
          <mesh geometry={nodes.Plane004_Grass_0.geometry} material={materials.Grass} position={[61.058, 20.193, -96.876]} rotation={[-Math.PI / 2, 0, 0]} scale={[7.714, 7.714, 3.403]} />
          <mesh geometry={nodes.Plane006_Grass_0.geometry} material={materials.Grass} position={[65.67, 18.167, -91.206]} rotation={[-Math.PI / 2, 0.198, 0.55]} scale={[6.029, 5.995, 3.376]} />
          <mesh geometry={nodes.Plane007_Grass_0.geometry} material={materials.Grass} position={[77.245, 14.863, -105.161]} rotation={[-1.651, 0.029, 1.795]} scale={[6.096, 6.096, 2.689]} />
          <mesh geometry={nodes.Plane008_Grass_0.geometry} material={materials.Grass} position={[80.756, 12.798, -109.558]} rotation={[-1.845, -0.015, 2.346]} scale={[4.765, 4.738, 2.668]} />
          <mesh geometry={nodes.Plane009_Grass_0.geometry} material={materials.Grass} position={[68.064, 2.039, -9.293]} rotation={[-Math.PI / 2, 0, 1.376]} scale={[7.714, 7.714, 5.216]} />
          <mesh geometry={nodes.Plane010_Grass_0.geometry} material={materials.Grass} position={[69.192, 3.62, -5.233]} rotation={[-1.398, 0.098, -0.508]} scale={[5.228, 5.198, 2.928]} />
          <mesh geometry={nodes.Plane011_Grass_0.geometry} material={materials.Grass} position={[10.457, -0.711, 49.015]} rotation={[-Math.PI / 2, 0, 1.376]} scale={[6.334, 6.334, 4.283]} />
          <mesh geometry={nodes.Plane012_Grass_0.geometry} material={materials.Grass} position={[11.383, 0.587, 52.35]} rotation={[-1.398, 0.098, -0.508]} scale={[4.293, 4.268, 2.404]} />
          <mesh geometry={nodes.Plane013_Grass_0.geometry} material={materials.Grass} position={[-20.945, -0.792, 77.239]} rotation={[-1.398, 0.098, -0.508]} scale={[4.755, 3.262, 2.893]} />
          <mesh geometry={nodes.Plane014_Grass_0.geometry} material={materials.Grass} position={[69.691, 19.594, -99.937]} rotation={[-Math.PI / 2, 0, -3.126]} scale={[9.251, 9.251, 4.081]} />
          <mesh geometry={nodes.Plane015_Grass_0.geometry} material={materials.Grass} position={[64.052, 17.164, -106.648]} rotation={[-1.568, -0.198, -2.575]} scale={[7.231, 7.189, 4.049]} />
          <mesh geometry={nodes.Plane016_Grass_0.geometry} material={materials.Grass} position={[75.842, 16.938, -94.241]} rotation={[-1.939, -0.004, -1.534]} scale={[6.875, 6.875, 3.033]} />
          <mesh geometry={nodes.Plane017_Grass_0.geometry} material={materials.Grass} position={[70.951, 16.779, -89.578]} rotation={[-1.74, 0.003, -0.984]} scale={[5.374, 5.342, 3.009]} />
          <mesh geometry={nodes.Plane018_Grass_0.geometry} material={materials.Grass} position={[69.823, 15.749, -108.625]} rotation={[-1.441, 0.15, -0.168]} scale={[7.231, 7.189, 4.049]} />
          <mesh geometry={nodes.Plane019_Grass_0.geometry} material={materials.Grass} position={[77.071, -1.512, 84.508]} rotation={[-1.567, 0.029, 1.975]} scale={[4.42, 4.395, 2.475]} />
          <mesh geometry={nodes.Plane020_Grass_0.geometry} material={materials.Grass} position={[74.577, -1.907, 78.385]} rotation={[-Math.PI / 2, 0, -1.703]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane021_Grass_0.geometry} material={materials.Grass} position={[69.425, -2.715, 82.442]} rotation={[-1.374, -0.026, -1.15]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane022_Grass_0.geometry} material={materials.Grass} position={[79.696, -2.88, 75.236]} rotation={[-1.623, -0.364, -0.12]} scale={[5.04, 5.04, 2.223]} />
          <mesh geometry={nodes.Plane023_Grass_0.geometry} material={materials.Grass} position={[68.616, -3.752, 78.044]} rotation={[-1.702, 0.149, 1.274]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane024_Grass_0.geometry} material={materials.Grass} position={[-75.399, -1.907, 83.858]} rotation={[-Math.PI / 2, 0, 0.146]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane025_Grass_0.geometry} material={materials.Grass} position={[-70.084, -2.715, 87.698]} rotation={[-1.6, 0.196, 0.699]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane026_Grass_0.geometry} material={materials.Grass} position={[-74.091, -3.752, 89.683]} rotation={[-1.68, -0.166, 3.104]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane027_Fence001_0.geometry} material={materials['Fence.001']} position={[76.254, 26.271, -64.811]} rotation={[-1.059, -0.052, -0.554]} scale={7.669} />
          <mesh geometry={nodes.Cube007_Rocks_0.geometry} material={materials.Rocks} position={[92.728, 17.606, -79.801]} rotation={[1.733, 0.279, -1.609]} scale={[5.795, 5.861, 8.44]} />
          <mesh geometry={nodes.Circle001_Balcony_0.geometry} material={materials.Balcony} position={[-41.401, 8.149, 28.668]} rotation={[-Math.PI / 2, 0, 0]} scale={40.43} />
          <mesh geometry={nodes.Cube027_WindmillWalls_0.geometry} material={materials.WindmillWalls} position={[-30.638, 102.498, 58.627]} rotation={[-Math.PI / 2, 0, -1.146]} scale={86.728} />
          <mesh geometry={nodes.Cone_Tiles_0.geometry} material={materials.Tiles} position={[-41.401, 150.12, 28.668]} rotation={[-Math.PI / 2, 0, 0]} scale={55.784} />
          <mesh geometry={nodes.Cube030_Tiles_0.geometry} material={materials.Tiles} position={[-40.439, 145.773, 39.037]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube031_Tiles_0.geometry} material={materials.Tiles} position={[-40.489, 122.915, 55.968]} rotation={[-1.099, 0, 0]} scale={129.27} />
          <mesh geometry={nodes.Cube008_WindowEmission_0.geometry} material={materials.WindowEmission} position={[-19.163, 95.496, 50.428]} rotation={[-Math.PI / 2, 0, 0.832]} scale={70.925} />
          <mesh geometry={nodes.Plane028_Grass_0.geometry} material={materials.Grass} position={[27.653, -1.512, 79.217]} rotation={[-1.594, 0.018, 3.046]} scale={[4.42, 4.395, 2.475]} />
          <mesh geometry={nodes.Plane029_Grass_0.geometry} material={materials.Grass} position={[21.084, -1.907, 78.467]} rotation={[-Math.PI / 2, 0, -0.633]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane030_Grass_0.geometry} material={materials.Grass} position={[22.171, -2.715, 84.933]} rotation={[-1.452, 0.16, -0.092]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane031_Grass_0.geometry} material={materials.Grass} position={[20.779, -2.88, 72.464]} rotation={[-1.271, -0.216, 0.993]} scale={[5.04, 5.04, 2.223]} />
          <mesh geometry={nodes.Plane032_Grass_0.geometry} material={materials.Grass} position={[17.924, -3.752, 83.533]} rotation={[-1.765, -0.042, 2.33]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane033_Grass_0.geometry} material={materials.Grass} position={[22.535, -1.512, 61.011]} rotation={[-1.593, -0.02, -1.862]} scale={[4.42, 4.395, 2.475]} />
          <mesh geometry={nodes.Plane034_Grass_0.geometry} material={materials.Grass} position={[20.528, -1.907, 67.31]} rotation={[-Math.PI / 2, 0, 0.743]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane035_Grass_0.geometry} material={materials.Grass} position={[27.082, -2.715, 67.495]} rotation={[-1.706, 0.146, 1.303]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane036_Grass_0.geometry} material={materials.Grass} position={[14.579, -2.88, 66.449]} rotation={[-1.293, 0.244, 2.302]} scale={[5.04, 5.04, 2.223]} />
          <mesh geometry={nodes.Plane037_Grass_0.geometry} material={materials.Grass} position={[24.887, -3.752, 71.39]} rotation={[-1.567, -0.198, -2.572]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane038_Grass_0.geometry} material={materials.Grass} position={[2.284, -0.471, 71.463]} rotation={[-1.556, -0.025, -0.475]} scale={[4.42, 4.395, 2.475]} />
          <mesh geometry={nodes.Plane039_Grass_0.geometry} material={materials.Grass} position={[8.107, -0.866, 74.593]} rotation={[-Math.PI / 2, 0, 2.129]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane040_Grass_0.geometry} material={materials.Grass} position={[9.493, -1.674, 68.184]} rotation={[-1.74, -0.105, 2.67]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane041_Grass_0.geometry} material={materials.Grass} position={[6.167, -1.84, 80.282]} rotation={[-1.771, 0.311, -2.53]} scale={[5.04, 5.04, 2.223]} />
          <mesh geometry={nodes.Plane042_Grass_0.geometry} material={materials.Grass} position={[12.919, -2.711, 71.058]} rotation={[-1.375, -0.033, -1.183]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane043_Grass_0.geometry} material={materials.Grass} position={[29.868, -1.512, 63.518]} rotation={[-1.591, -0.021, -1.787]} scale={[4.42, 4.395, 2.475]} />
          <mesh geometry={nodes.Plane044_Grass_0.geometry} material={materials.Grass} position={[27.56, -1.907, 70.618]} rotation={[-Math.PI / 2, 0, 0.817]} scale={[5.524, 5.524, 2.992]} />
          <mesh geometry={nodes.Plane045_Grass_0.geometry} material={materials.Grass} position={[34.883, -2.715, 69.648]} rotation={[-1.716, 0.135, 1.377]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane046_Grass_0.geometry} material={materials.Grass} position={[32.982, -3.752, 73.695]} rotation={[-1.552, -0.198, -2.497]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane047_Grass_0.geometry} material={materials.Grass} position={[11.178, -1.512, 66.409]} rotation={[-1.554, -0.024, -0.411]} scale={[4.42, 4.395, 2.475]} />
          <mesh geometry={nodes.Plane048_Grass_0.geometry} material={materials.Grass} position={[17.19, -1.907, 69.159]} rotation={[-Math.PI / 2, 0, 2.194]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane049_Grass_0.geometry} material={materials.Grass} position={[18.162, -2.715, 62.675]} rotation={[-1.733, -0.115, 2.734]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane050_Grass_0.geometry} material={materials.Grass} position={[19.118, -0.471, 87.77]} rotation={[-1.544, 0.012, 0.975]} scale={[4.42, 4.395, 2.475]} />
          <mesh geometry={nodes.Plane051_Grass_0.geometry} material={materials.Grass} position={[22.926, -0.866, 82.366]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane052_Grass_0.geometry} material={materials.Grass} position={[16.73, -1.674, 80.219]} rotation={[-1.486, -0.179, -2.146]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane053_Grass_0.geometry} material={materials.Grass} position={[28.34, -1.84, 84.976]} rotation={[-1.907, -0.151, -1.137]} scale={[5.04, 5.04, 2.223]} />
          <mesh geometry={nodes.Plane054_Grass_0.geometry} material={materials.Grass} position={[20.769, -2.711, 76.495]} rotation={[-1.514, 0.19, 0.258]} scale={[4.349, 4.305, 2.949]} />
          <mesh geometry={nodes.Plane055_Grass_0.geometry} material={materials.Grass} position={[-88.028, -1.512, 79.217]} rotation={[-1.594, 0.018, 3.046]} scale={[4.42, 4.395, 2.475]} />
          <mesh geometry={nodes.Plane056_Grass_0.geometry} material={materials.Grass} position={[-95.153, -1.907, 67.31]} rotation={[-Math.PI / 2, 0, 0.743]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane057_Grass_0.geometry} material={materials.Grass} position={[-90.794, -3.752, 71.39]} rotation={[-1.567, -0.198, -2.572]} scale={[5.301, 5.27, 2.968]} />
          <mesh geometry={nodes.Plane060_Grass_0.geometry} material={materials.Grass} position={[-87.348, -1.907, 69.949]} rotation={[-Math.PI / 2, 0, 0.817]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane061_Grass_0.geometry} material={materials.Grass} position={[-92.755, -0.866, 82.366]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[6.782, 6.782, 2.992]} />
          <mesh geometry={nodes.Plane058_Grass_0.geometry} material={materials.Grass} position={[82.913, 2.132, 3.047]} rotation={[-1.396, 0.024, 3.072]} scale={[4.978, 4.949, 2.787]} />
          <mesh geometry={nodes.Plane059_Grass_0.geometry} material={materials.Grass} position={[75.493, 1.874, 2.329]} rotation={[-1.372, 0.007, -0.607]} scale={[7.638, 7.638, 3.369]} />
          <mesh geometry={nodes.Plane062_Grass_0.geometry} material={materials.Grass} position={[76.617, 6.201, -16.889]} rotation={[-1.393, -0.013, -1.835]} scale={[4.978, 4.949, 2.787]} />
          <mesh geometry={nodes.Plane063_Grass_0.geometry} material={materials.Grass} position={[75.858, 4.363, -8.69]} rotation={[-1.372, 0.007, 0.769]} scale={[6.109, 6.116, 3.345]} />
          <mesh geometry={nodes.Plane064_Grass_0.geometry} material={materials.Grass} position={[79.552, 1.409, -6.006]} rotation={[-1.362, -0.191, -2.546]} scale={[5.97, 5.936, 3.343]} />
          <mesh geometry={nodes.Plane065_Grass_0.geometry} material={materials.Grass} position={[60.777, 3.909, -1.321]} rotation={[-1.372, 0.007, 2.155]} scale={[7.638, 7.638, 3.369]} />
          <mesh geometry={nodes.Plane066_Grass_0.geometry} material={materials.Grass} position={[84.946, 5.629, -14.344]} rotation={[-1.391, -0.015, -1.761]} scale={[4.978, 4.949, 2.787]} />
          <mesh geometry={nodes.Plane067_Grass_0.geometry} material={materials.Grass} position={[83.403, 3.762, -7.29]} rotation={[-1.372, 0.007, 0.843]} scale={[7.638, 7.638, 3.369]} />
          <mesh geometry={nodes.Plane068_Grass_0.geometry} material={materials.Grass} position={[88.768, 2.926, -7.125]} rotation={[-1.521, 0.138, 1.404]} scale={[4.752, 4.752, 3.33]} />
          <mesh geometry={nodes.Plane069_Grass_0.geometry} material={materials.Grass} position={[88.733, 0.881, -3.707]} rotation={[-1.348, -0.19, -2.47]} scale={[5.97, 5.936, 3.343]} />
          <mesh geometry={nodes.Plane070_Grass_0.geometry} material={materials.Grass} position={[70.836, 3.957, -7.824]} rotation={[-1.372, 0.007, 2.22]} scale={[7.638, 7.638, 3.369]} />
          <mesh geometry={nodes.Plane071_Grass_0.geometry} material={materials.Grass} position={[73.562, 1.388, 12.975]} rotation={[-1.345, 0.02, 1.001]} scale={[4.978, 4.949, 2.787]} />
          <mesh geometry={nodes.Plane072_Grass_0.geometry} material={materials.Grass} position={[78.364, 2.151, 4.658]} rotation={[-1.372, 0.007, -2.678]} scale={[6.09, 6.135, 3.345]} />
          <mesh geometry={nodes.Plane073_Grass_0.geometry} material={materials.Grass} position={[70.644, 1.748, 4.446]} rotation={[-1.282, -0.17, -2.12]} scale={[5.97, 5.936, 3.343]} />
          <mesh geometry={nodes.Plane074_Grass_0.geometry} material={materials.Grass} position={[83.852, 0.484, 9.308]} rotation={[-1.704, -0.154, -1.11]} scale={[5.676, 5.676, 2.504]} />
          <mesh geometry={nodes.Plane075_Grass_0.geometry} material={materials.Grass} position={[-68.933, 3.048, -102.106]} rotation={[-1.567, 0.024, 3.072]} scale={[5.502, 5.47, 3.081]} />
          <mesh geometry={nodes.Plane076_Grass_0.geometry} material={materials.Grass} position={[-77.134, 2.632, -102.839]} rotation={[-1.543, 0.007, -0.607]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane077_Grass_0.geometry} material={materials.Grass} position={[-75.891, 3.709, -124.586]} rotation={[-1.565, -0.013, -1.835]} scale={[5.502, 5.47, 3.081]} />
          <mesh geometry={nodes.Plane078_Grass_0.geometry} material={materials.Grass} position={[-78.187, 3.018, -116.698]} rotation={[-1.543, 0.007, 0.769]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane079_Grass_0.geometry} material={materials.Grass} position={[-72.647, 0.549, -111.828]} rotation={[-1.534, -0.191, -2.546]} scale={[6.599, 6.561, 3.695]} />
          <mesh geometry={nodes.Plane080_Grass_0.geometry} material={materials.Grass} position={[-88.298, 1.315, -104.601]} rotation={[-1.543, 0.007, 2.155]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane081_Grass_0.geometry} material={materials.Grass} position={[-66.685, 3.568, -121.707]} rotation={[-1.563, -0.015, -1.761]} scale={[5.502, 5.47, 3.081]} />
          <mesh geometry={nodes.Plane082_Grass_0.geometry} material={materials.Grass} position={[-68.39, 2.868, -113.671]} rotation={[-1.543, 0.007, 0.843]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane083_Grass_0.geometry} material={materials.Grass} position={[-60.256, 1.824, -114.286]} rotation={[-1.693, 0.138, 1.404]} scale={[6.599, 6.561, 3.695]} />
          <mesh geometry={nodes.Plane084_Grass_0.geometry} material={materials.Grass} position={[-62.499, 0.409, -109.225]} rotation={[-1.52, -0.19, -2.47]} scale={[6.599, 6.561, 3.695]} />
          <mesh geometry={nodes.Plane085_Grass_0.geometry} material={materials.Grass} position={[-82.281, 2.98, -114.29]} rotation={[-1.543, 0.007, 2.22]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane086_Grass_0.geometry} material={materials.Grass} position={[-79.268, 4.115, -91.153]} rotation={[-1.517, 0.02, 1.001]} scale={[5.502, 5.47, 3.081]} />
          <mesh geometry={nodes.Plane087_Grass_0.geometry} material={materials.Grass} position={[-74.707, 3.78, -98.013]} rotation={[-1.543, 0.007, -2.678]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane088_Grass_0.geometry} material={materials.Grass} position={[-82.493, 2.894, -100.51]} rotation={[-1.454, -0.17, -2.12]} scale={[6.599, 6.561, 3.695]} />
          <mesh geometry={nodes.Plane089_Grass_0.geometry} material={materials.Grass} position={[-67.894, 2.438, -94.976]} rotation={[-1.876, -0.154, -1.11]} scale={[6.273, 6.273, 2.767]} />
          <mesh geometry={nodes.Plane090_Grass_0.geometry} material={materials.Grass} position={[-86.489, 2.163, -25.373]} rotation={[-1.434, 0.007, 2.155]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane091_Grass_0.geometry} material={materials.Grass} position={[-79.052, 3.713, -36.214]} rotation={[-1.543, 0.007, -2.678]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane092_Grass_0.geometry} material={materials.Grass} position={[-63.614, 3.638, -63.964]} rotation={[-1.596, 0.013, 1.806]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane093_Grass_0.geometry} material={materials.Grass} position={[-62.211, 4.786, -69.18]} rotation={[-1.596, 0.013, -0.264]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane094_Grass_0.geometry} material={materials.Grass} position={[-89.449, 2.45, -60.291]} rotation={[-1.596, 0.013, 1.806]} scale={[8.442, 8.442, 3.724]} />
          <mesh geometry={nodes.Plane095_Grass_0.geometry} material={materials.Grass} position={[80.123, 10.632, -53.852]} rotation={[-1.372, 0.007, 0.769]} scale={[7.638, 7.638, 3.369]} />
          <mesh geometry={nodes.Plane096_Grass_0.geometry} material={materials.Grass} position={[83.746, 10.815, -52.133]} rotation={[-1.391, -0.015, -1.761]} scale={[4.978, 4.949, 2.787]} />
          <mesh geometry={nodes.Plane097_Grass_0.geometry} material={materials.Grass} position={[-7.588, -1.592, -5.922]} rotation={[-Math.PI / 2, 0, -1.974]} scale={[6.334, 6.334, 4.283]} />
          <mesh geometry={nodes.Plane098_Grass_0.geometry} material={materials.Grass} position={[-7.805, -0.293, -9.375]} rotation={[-1.76, -0.061, 2.428]} scale={[4.293, 4.268, 2.404]} />
        </group>
      </group>
  )
}

useGLTF.preload('./models/wheat_farm_at_sunset.glb')